import json,cv2,numpy as np
from pathlib import Path
from scipy.optimize import least_squares
P=Path(__file__).resolve().parent;c=json.loads((P/'capture.json').read_text());out={'method':'deterministic multistart robust sphere fit to eroded visible mask; geometric approximation, not proof of true fruit center','erosion_pixels':7,'loss':'soft_l1','loss_scale_m':.002,'frames':[]};roi=[(300,270,320,290),(290,360,320,380),(170,200,190,230)];table=[]
for r in c['records']:
 if r['sync_error_s']>1e-6:continue
 im=cv2.imread(str(P/f"rgb_{r['index']:02d}.jpg"));d=np.load(P/f"depth_{r['index']:02d}.npy");hsv=cv2.cvtColor(im,cv2.COLOR_BGR2HSV);mask=cv2.inRange(hsv,(3,90,60),(30,255,255));cs,_=cv2.findContours(mask,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE);cont=max([x for x in cs if cv2.contourArea(x)>2000],key=lambda x:cv2.boundingRect(x)[0]);m=np.zeros(d.shape,np.uint8);cv2.drawContours(m,[cont],-1,255,-1);m=cv2.erode(m,np.ones((7,7),np.uint8));yy,xx=np.where((m>0)&(d>0));z=d[yy,xx]*.001;median=np.median(z);keep=np.abs(z-median)<.08;xx,yy,z=xx[keep][::2],yy[keep][::2],z[keep][::2];k=r['K'];T=np.array(r['camera_to_base']);points=np.c_[(xx-k[2])*z/k[0],(yy-k[5])*z/k[4],z];ray=np.median(points,axis=0);ray=ray/np.linalg.norm(ray);surface=np.median(points,axis=0);fits=[]
 for rad in [.025,.035,.045,.06]:
  init=np.r_[surface+ray*rad,rad];fit=least_squares(lambda x:np.linalg.norm(points-x[:3],axis=1)-x[3],init,loss='soft_l1',f_scale=.002,bounds=(np.r_[surface-.15,.005],np.r_[surface+.15,.12]),max_nfev=300);res=np.linalg.norm(points-fit.x[:3],axis=1)-fit.x[3];base=T@np.r_[fit.x[:3],1];fits.append({'initial_radius_m':rad,'center_base_m':base[:3].tolist(),'radius_m':float(fit.x[3]),'rmse_mm':float(np.sqrt(np.mean(res**2))*1000),'median_abs_residual_mm':float(np.median(np.abs(res))*1000),'p95_abs_residual_mm':float(np.percentile(np.abs(res),95)*1000),'fraction_within_3mm':float(np.mean(np.abs(res)<=.003)),'success':bool(fit.success)})
 rr={'index':r['index'],'points':len(points),'eroded_valid_fraction':float(np.mean(d[m>0]>0)),'fits':fits};out['frames'].append(rr)
 uv=np.array([(x,y) for x0,y0,x1,y1 in roi for y in range(y0,y1,2) for x in range(x0,x1,2)]);z=d[uv[:,1],uv[:,0]]*.001;uv=uv[z>0];z=z[z>0];cam=np.c_[(uv[:,0]-k[2])*z/k[0],(uv[:,1]-k[5])*z/k[4],z];table.append(cam@T[:3,:3].T+T[:3,3])
t=np.vstack(table);A=np.c_[t[:,:2],np.ones(len(t))];coef=np.linalg.lstsq(A,t[:,2],rcond=None)[0];out['local_table']={'rois':roi,'coefficients_z_ax_by_c':coef.tolist(),'rmse_mm':float(np.sqrt(np.mean((A@coef-t[:,2])**2))*1000)}
a=np.array([r['fits'][0]['center_base_m'] for r in out['frames']]);rads=np.array([r['fits'][0]['radius_m'] for r in out['frames']]);center=np.median(a,0);surface=np.array(json.loads((P/'contour_localization.json').read_text())['right_target_surface_median_m']);out.update(center_median_m=center.tolist(),center_span_mm=(np.ptp(a,axis=0)*1000).tolist(),radius_range_mm=(np.array([rads.min(),rads.max()])*1000).tolist(),multistart_max_center_span_mm=max(float(np.linalg.norm(np.ptp(np.array([x['center_base_m'] for x in r['fits']]),axis=0))*1000) for r in out['frames']),sphere_center_minus_surface_mm=((center-surface)*1000).tolist(),sphere_bottom_minus_local_table_mm=float((center[2]-np.median(rads)-np.r_[center[:2],1]@coef)*1000))
(P/'sphere_diagnostic.json').write_text(json.dumps(out,indent=2));print(json.dumps({k:v for k,v in out.items() if k!='frames'},indent=2))
